name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  frontend-eslint:
    name: Frontend Lint (ESLint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

  backend-phpunit:
    name: Backend Tests (PHPUnit)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_mysql
          coverage: none
          tools: composer
      - name: Validate composer.json
        run: composer validate --no-interaction
      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist
      - name: PHP syntax check
        shell: bash
        run: |
          set -e
          find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l
      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox